UI: Created Home Page | Issue - #4
AOSP-NIT-Surat/Bookstore-Android pull request #6
Opened 2021-10-03 07:12 UTC by unnikrishnan2002

- Floating Action button added with book selling option
- Search bar added at the top of the page

2021-10-03 11:59 UTC, Mustafa2856 commented on .idea/runConfigurations.xml
> -<?xml version="1.0" encoding="UTF-8"?>
restore this file

2021-10-03 12:04 UTC, Mustafa2856 commented on app/src/main/java/com/aosp/bookstore/MainActivity.java
> +
Don't add unnecessary newlines

2021-10-03 12:12 UTC, Mustafa2856 requested changes

2021-10-03 12:12 UTC, Mustafa2856 commented on app/src/main/java/com/aosp/bookstore/MainActivity.java
> +
Don't add unnecessary empty lines between variable declarations.

2021-10-03 12:12 UTC, Mustafa2856 commented on .idea/runConfigurations.xml
> -<?xml version="1.0" encoding="UTF-8"?>
Restore this file

2021-10-03 12:12 UTC, Mustafa2856 commented on app/src/main/java/com/aosp/bookstore/MainActivity.java
>  }
add newlines after each file

2021-10-03 12:12 UTC, Mustafa2856 commented on app/src/main/java/com/aosp/bookstore/MainActivity.java
> +        sellBook.setOnClickListener(new View.OnClickListener() {
use lambda functions for anonymous calls

2021-10-03 12:12 UTC, Mustafa2856 commented on app/src/main/java/com/aosp/bookstore/MainActivity.java
> +        expand.setOnClickListener(new View.OnClickListener() {
use lambda functions for anonymous calls

2021-10-03 12:12 UTC, Mustafa2856 commented on app/src/main/res/layout/activity_main.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
unnecessary change in syntax for first 10 lines

2021-10-03 12:12 UTC, Mustafa2856 commented on app/src/main/res/layout/activity_main.xml
>      <TextView
the welcome text was place holder, no longer needed, add a scroll view here to show search results

2021-10-03 12:12 UTC, Mustafa2856 commented on app/src/main/res/layout/activity_main.xml
> +        android:hint="  Search..."
make hint to be "search books available"

2021-10-03 14:26 UTC, unnikrishnan2002 commented
@Mustafa2856 All the requested changes have been made, added the runConfigurations.xml file, and **I had to change the versions of some dependencies because it was throwing errors otherwise**

2021-10-04 04:05 UTC, Mustafa2856 approved these changes

2021-10-04 04:06 UTC, merged